[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
educhain = "3WXZzDFmMAv6z69NQZNhV2YLMMWc7khQNRfyei2VCZmi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devWallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
