[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
educhain = "EQTpUfQNeenySvPPvwYw9rfyjC6gPNhnR7YikL8Y41m9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devWallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
