import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import './global.css'
import Navbar from './components/topBar'
import { ModalsProvider } from './context/modals'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = (props: PropsWithChildren) => {
  const { children } = props
  return (
    <html lang="en">
      <body>
        <ModalsProvider>
          <Navbar />
          {children}
        </ModalsProvider>
      </body>
    </html>
  );
}

export default RootLayout
